-- Migration: AddDisplayOrderToRolePage
-- Adds display_order column and sets ordering for nav bar pages
-- Run against Neon cloud PostgreSQL

-- 0. Rename the old Leagues page to Dashboard (from earlier route rename)
UPDATE scorecast.page_master
SET page_code = 'DASHBOARD',
    page_name = 'Dashboard',
    page_url = '/dashboard',
    modified_date = now(),
    modified_by = 'migration'
WHERE page_url = '/leagues' OR page_code = 'LEAGUES';

-- Also update the league detail child page route
UPDATE scorecast.page_master
SET page_url = '/dashboard/{LeagueId}',
    modified_date = now(),
    modified_by = 'migration'
WHERE page_url = '/leagues/{LeagueId}';

-- 1. Add the column (idempotent)
ALTER TABLE scorecast.role_page ADD COLUMN IF NOT EXISTS display_order integer NOT NULL DEFAULT 0;

-- 2. Set display order for all role_page entries based on page URL
-- Dashboard first, then main user pages, admin pages last
UPDATE scorecast.role_page rp
SET display_order = sort.new_order,
    modified_date = now(),
    modified_by = 'migration'
FROM scorecast.page_master pm
JOIN (VALUES
    ('/dashboard',    1),
    ('/predict',      2),
    ('/scores',       3),
    ('/points-table', 4),
    ('/player-stats', 5),
    ('/data-sync',    6)
) AS sort(page_url, new_order) ON pm.page_url = sort.page_url
WHERE rp.page_id = pm.id;

-- 3. Also create the match_lineup table if not exists (bundled in same EF migration)
CREATE TABLE IF NOT EXISTS scorecast.match_lineup (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    match_id bigint NOT NULL,
    player_id bigint NOT NULL,
    is_starter boolean NOT NULL,
    created_by character varying(50) NOT NULL DEFAULT current_user,
    created_date timestamp with time zone NOT NULL DEFAULT now(),
    created_by_app character varying(100) NOT NULL,
    modified_by character varying(50) NOT NULL DEFAULT current_user,
    modified_date timestamp with time zone NOT NULL DEFAULT now(),
    modified_by_app character varying(100),
    is_deleted boolean NOT NULL DEFAULT false,
    CONSTRAINT "PK_match_lineup" PRIMARY KEY (id),
    CONSTRAINT "FK_match_lineup_match_match_id" FOREIGN KEY (match_id) REFERENCES scorecast.match(id) ON DELETE RESTRICT,
    CONSTRAINT "FK_match_lineup_player_player_id" FOREIGN KEY (player_id) REFERENCES scorecast.player(id) ON DELETE RESTRICT
);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_match_lineup_match_id_player_id" ON scorecast.match_lineup (match_id, player_id);
CREATE INDEX IF NOT EXISTS "IX_match_lineup_player_id" ON scorecast.match_lineup (player_id);

-- 4. Record migration in EF history
INSERT INTO scorecast.sc_db_migrations_history ("MigrationId", "ProductVersion")
VALUES ('20260315190600_AddDisplayOrderToRolePage', '10.0.4')
ON CONFLICT DO NOTHING;
