DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'scorecast') THEN
        CREATE SCHEMA scorecast;
    END IF;
END $EF$;
CREATE TABLE IF NOT EXISTS scorecast.sc_db_migrations_history (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK_sc_db_migrations_history" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'scorecast') THEN
        CREATE SCHEMA scorecast;
    END IF;
END $EF$;

CREATE TABLE scorecast.user_master (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    keycloak_user_id character varying(50) NOT NULL,
    user_id character varying(100) NOT NULL,
    email character varying(255) NOT NULL,
    display_name character varying(100),
    avatar_url character varying(500),
    favorite_team character varying(100),
    total_points integer NOT NULL DEFAULT 0,
    current_streak integer NOT NULL DEFAULT 0,
    longest_streak integer NOT NULL DEFAULT 0,
    is_active boolean NOT NULL DEFAULT TRUE,
    created_by character varying(50) NOT NULL DEFAULT (current_user),
    created_date timestamp with time zone NOT NULL DEFAULT (now()),
    created_by_app character varying(100) NOT NULL,
    modified_by character varying(50) NOT NULL DEFAULT (current_user),
    modified_date timestamp with time zone NOT NULL DEFAULT (now()),
    modified_by_app character varying(100),
    is_deleted boolean NOT NULL DEFAULT FALSE,
    CONSTRAINT "PK_user_master" PRIMARY KEY (id)
);

CREATE UNIQUE INDEX "IX_user_master_email" ON scorecast.user_master (email);

CREATE UNIQUE INDEX "IX_user_master_keycloak_user_id" ON scorecast.user_master (keycloak_user_id);

CREATE UNIQUE INDEX "IX_user_master_user_id" ON scorecast.user_master (user_id);

INSERT INTO scorecast.sc_db_migrations_history ("MigrationId", "ProductVersion")
VALUES ('20260312213930_InitialCreate', '10.0.4');

COMMIT;

